# Exploratory Data Analysis
In this notebook, we will perform some exploratory data analysis. The dataset used in this notebook is modified from the original dataset, which we created after feature extraction and dataframe formation from the logfile text document.

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd

pd.set_option('display.max_columns', None)
df = pd.read_csv('/content/drive/MyDrive/log_og v2.csv')
df

,type,subtype,level,srccountry,srcintf,srcintfrole,dstintf,dstintfrole,action,proto,service,policyid,srcport,dstport,appcat,duration,sentbyte,rcvdbyte,crscore
0,traffic,forward,notice,India,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,HTTPS,49.0,30390.0,443.0,NaN,13.0,1097.0,9182.0,NaN
1,traffic,forward,notice,India,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,HTTPS,59.0,9570.0,443.0,NaN,14.0,424.0,8589.0,NaN
2,traffic,forward,notice,Reserved,Local_LAN,undefined,LLB- Connect,wan,close,6.0,HTTPS,57.0,49642.0,443.0,unscanned,1.0,1728.0,5255.0,NaN
3,traffic,forward,notice,India,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,HTTPS,49.0,1204.0,443.0,NaN,24.0,356.0,6708.0,NaN
4,traffic,forward,notice,Reserved,Local_LAN,undefined,LLB- Connect,wan,close,6.0,HTTPS,57.0,49651.0,443.0,unscanned,1.0,1728.0,5175.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380832,traffic,forward,notice,United Kingdom,LLB- Connect,wan,Local_LAN,undefined,accept,1.0,PING,49.0,NaN,NaN,NaN,70.0,132.0,172.0,NaN
380833,traffic,forward,notice,India,LLB- Connect,wan,Local_LAN,undefined,close,6.0,HTTPS,60.0,52867.0,443.0,NaN,3.0,416.0,9096.0,NaN
380834,traffic,forward,notice,United States,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,HTTPS,67.0,17191.0,443.0,NaN,6.0,216.0,248.0,NaN
380835,traffic,forward,notice,India,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,HTTPS,49.0,57934.0,443.0,NaN,19.0,320.0,2530.0,NaN
380836,traffic,forward,notice,India,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,FTPS,63.0,3082.0,990.0,NaN,6.0,124.0,244.0,NaN

In [7]:
def unique(df):
  for col in df.columns:
    print(f'{col}')
    print()
    print(df[col].value_counts())
    print('\n')
    print('_'*100)

unique(df)

type

traffic    378834
event        2000
utm             3
Name: type, dtype: int64


____________________________________________________________________________________________________
subtype

forward    378528
system       2000
local         306
ips             3
Name: subtype, dtype: int64


____________________________________________________________________________________________________
level

notice      378635
error         1859
warning        339
alert            3
critical         1
Name: level, dtype: int64


____________________________________________________________________________________________________
srccountry

India            206270
United States     73812
Reserved          37919
Australia          7711
Ireland            6552
                  ...
Kenya                 1
Ecuador               1
Belize                1
Kyrgyzstan            1
Benin                 1
Name: srccountry, Length: 92, dtype: int64


____________________________________________________________________________________________________
srcintf

LLB- Connect    344217
Local_LAN        34314
unknown-0          280
root                26
Name: srcintf, dtype: int64


____________________________________________________________________________________________________
srcintfrole

wan          344217
undefined     34620
Name: srcintfrole, dtype: int64


____________________________________________________________________________________________________
dstintf

Local_LAN       344243
LLB- Connect     34594
Name: dstintf, dtype: int64


____________________________________________________________________________________________________
dstintfrole

undefined    344243
wan           34594
Name: dstintfrole, dtype: int64


____________________________________________________________________________________________________
action

client-rst     138955
accept         101654
close           95831
server-rst      25569
deny            10236
timeout          6250
ip-conn           230
perf-stats        124
dns               109
alert-email        10
roll-log            6
dropped             3
Name: action, dtype: int64


____________________________________________________________________________________________________
proto

6.0     283409
1.0      93850
17.0      1566
47.0        12
Name: proto, dtype: int64


____________________________________________________________________________________________________
service

HTTPS          251556
PING            93697
FTPS            14699
NHP-FLUX         4188
ForFTP_DATA      2154
                ...
tcp/8092            1
tcp/11119           1
tcp/28573           1
tcp/52526           1
tcp/10223           1
Name: service, Length: 935, dtype: int64


____________________________________________________________________________________________________
policyid

49.0    98170
59.0    45273
57.0    33024
47.0    30732
67.0    23028
60.0    19614
63.0    16804
35.0    15688
33.0    11528
34.0    11473
50.0    11457
44.0    10667
17.0     9383
56.0     7919
53.0     6365
39.0     6303
42.0     5716
48.0     3486
89.0     3234
72.0     2405
79.0     1928
52.0      949
85.0      754
87.0      635
43.0      341
0.0       306
54.0      297
75.0      251
90.0      240
82.0      203
74.0      186
73.0      157
37.0      133
76.0       55
86.0       46
80.0       36
71.0       25
81.0       18
78.0        3
88.0        2
77.0        2
65.0        1
Name: policyid, dtype: int64


____________________________________________________________________________________________________
srcport

47786.0    371
49494.0    350
48644.0    344
49350.0    330
46587.0    311
          ...
5462.0       1
43905.0      1
15932.0      1
39441.0      1
15267.0      1
Name: srcport, Length: 53218, dtype: int64


____________________________________________________________________________________________________
dstport

443.0      251557
990.0       14699
6785.0       4188
80.0         1864
53.0         1120
            ...
8516.0          1
8092.0          1
11119.0         1
65153.0         1
10223.0         1
Name: dstport, Length: 950, dtype: int64


____________________________________________________________________________________________________
appcat

unscanned    62014
Name: appcat, dtype: int64


____________________________________________________________________________________________________
duration

60.0       88693
1.0        49150
6.0        34613
5.0        12645
0.0        10432
           ...
701.0          1
2412.0         1
48720.0        1
2411.0         1
60168.0        1
Name: duration, Length: 1327, dtype: int64


____________________________________________________________________________________________________
sentbyte

36.0         84466
164.0        28431
268.0        28186
216.0        15022
132.0        12430
             ...
3092.0           1
2199.0           1
650.0            1
3028.0           1
1626171.0        1
Name: sentbyte, Length: 2712, dtype: int64


____________________________________________________________________________________________________
rcvdbyte

36.0       84466
168.0      21201
248.0      13482
132.0      11915
0.0        11058
           ...
12500.0        1
24132.0        1
14218.0        1
14077.0        1
14840.0        1
Name: rcvdbyte, Length: 15007, dtype: int64


____________________________________________________________________________________________________
crscore

30.0    10238
5.0      6549
50.0        4
Name: crscore, dtype: int64


____________________________________________________________________________________________________

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380837 entries, 0 to 380836
Data columns (total 19 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   type         380837 non-null  object
 1   subtype      380837 non-null  object
 2   level        380837 non-null  object
 3   srccountry   378498 non-null  object
 4   srcintf      378837 non-null  object
 5   srcintfrole  378837 non-null  object
 6   dstintf      378837 non-null  object
 7   dstintfrole  378837 non-null  object
 8   action       378977 non-null  object
 9   proto        378837 non-null  float64
 10  service      378837 non-null  object
 11  policyid     378837 non-null  float64
 12  srcport      284987 non-null  float64
 13  dstport      284987 non-null  float64
 14  appcat       62014 non-null   object
 15  duration     378495 non-null  float64
 16  sentbyte     378495 non-null  float64
 17  rcvdbyte     378495 non-null  float64
 18  crscore      16791 non-null   float64
dtypes: float64(8), object(11)
memory usage: 55.2+ MB

In [9]:
df.isnull().sum()

type                0
subtype             0
level               0
srccountry       2339
srcintf          2000
srcintfrole      2000
dstintf          2000
dstintfrole      2000
action           1860
proto            2000
service          2000
policyid         2000
srcport         95850
dstport         95850
appcat         318823
duration         2342
sentbyte         2342
rcvdbyte         2342
crscore        364046
dtype: int64

In [10]:
df.crscore.value_counts()

30.0    10238
5.0      6549
50.0        4
Name: crscore, dtype: int64

In [11]:
df.crscore.fillna(0, inplace=True)
df.isnull().sum()

type                0
subtype             0
level               0
srccountry       2339
srcintf          2000
srcintfrole      2000
dstintf          2000
dstintfrole      2000
action           1860
proto            2000
service          2000
policyid         2000
srcport         95850
dstport         95850
appcat         318823
duration         2342
sentbyte         2342
rcvdbyte         2342
crscore             0
dtype: int64

In [12]:
df.isna().sum()

type                0
subtype             0
level               0
srccountry       2339
srcintf          2000
srcintfrole      2000
dstintf          2000
dstintfrole      2000
action           1860
proto            2000
service          2000
policyid         2000
srcport         95850
dstport         95850
appcat         318823
duration         2342
sentbyte         2342
rcvdbyte         2342
crscore             0
dtype: int64

In [13]:
df = df[~df.srcintf.isna()]
df.isna().sum()

type                0
subtype             0
level               0
srccountry        339
srcintf             0
srcintfrole         0
dstintf             0
dstintfrole         0
action              0
proto               0
service             0
policyid            0
srcport         93850
dstport         93850
appcat         316823
duration          342
sentbyte          342
rcvdbyte          342
crscore             0
dtype: int64

In [14]:
df.srccountry.fillna('Unknown', inplace=True)
df.isna().sum()

<ipython-input-14-3820e1f87f26>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.srccountry.fillna('Unknown', inplace=True)

type                0
subtype             0
level               0
srccountry          0
srcintf             0
srcintfrole         0
dstintf             0
dstintfrole         0
action              0
proto               0
service             0
policyid            0
srcport         93850
dstport         93850
appcat         316823
duration          342
sentbyte          342
rcvdbyte          342
crscore             0
dtype: int64

In [15]:
df.duration.fillna(0, inplace=True)
df.sentbyte.fillna(0, inplace=True)
df.rcvdbyte.fillna(0, inplace=True)
df.isna().sum()

<ipython-input-15-fd9311f7e06c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.duration.fillna(0, inplace=True)
<ipython-input-15-fd9311f7e06c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sentbyte.fillna(0, inplace=True)
<ipython-input-15-fd9311f7e06c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rcvdbyte.fillna(0, inplace=True)

type                0
subtype             0
level               0
srccountry          0
srcintf             0
srcintfrole         0
dstintf             0
dstintfrole         0
action              0
proto               0
service             0
policyid            0
srcport         93850
dstport         93850
appcat         316823
duration            0
sentbyte            0
rcvdbyte            0
crscore             0
dtype: int64

In [16]:
df.appcat = df.appcat.apply(lambda x: 1 if x == 'unscanned' else 0)

<ipython-input-16-b6cd7b486148>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.appcat = df.appcat.apply(lambda x: 1 if x == 'unscanned' else 0)

In [17]:
df.isna().sum()

type               0
subtype            0
level              0
srccountry         0
srcintf            0
srcintfrole        0
dstintf            0
dstintfrole        0
action             0
proto              0
service            0
policyid           0
srcport        93850
dstport        93850
appcat             0
duration           0
sentbyte           0
rcvdbyte           0
crscore            0
dtype: int64

In [18]:
cp = df.drop(['srcport','dstport'], axis=1)
cp.isna().sum()

type           0
subtype        0
level          0
srccountry     0
srcintf        0
srcintfrole    0
dstintf        0
dstintfrole    0
action         0
proto          0
service        0
policyid       0
appcat         0
duration       0
sentbyte       0
rcvdbyte       0
crscore        0
dtype: int64

We have successfully removed and/or filled the missing values in the dataset. Thus we are left with a clean dataset, which can now be mapped and encoded in order to be used in our machine learning model.

---

In [19]:
cp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 378837 entries, 0 to 380836
Data columns (total 17 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   type         378837 non-null  object
 1   subtype      378837 non-null  object
 2   level        378837 non-null  object
 3   srccountry   378837 non-null  object
 4   srcintf      378837 non-null  object
 5   srcintfrole  378837 non-null  object
 6   dstintf      378837 non-null  object
 7   dstintfrole  378837 non-null  object
 8   action       378837 non-null  object
 9   proto        378837 non-null  float64
 10  service      378837 non-null  object
 11  policyid     378837 non-null  float64
 12  appcat       378837 non-null  int64
 13  duration     378837 non-null  float64
 14  sentbyte     378837 non-null  float64
 15  rcvdbyte     378837 non-null  float64
 16  crscore      378837 non-null  float64
dtypes: float64(6), int64(1), object(10)
memory usage: 52.0+ MB

In [20]:
cp.crscore.value_counts()

0.0     362046
30.0     10238
5.0       6549
50.0         4
Name: crscore, dtype: int64

In [21]:
cp[cp.crscore == 50]

,type,subtype,level,srccountry,srcintf,srcintfrole,dstintf,dstintfrole,action,proto,service,policyid,appcat,duration,sentbyte,rcvdbyte,crscore
276767,utm,ips,alert,Japan,LLB- Connect,wan,Local_LAN,undefined,dropped,6.0,HTTPS,34.0,0,0.0,0.0,0.0,50.0
277696,traffic,forward,notice,Japan,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,HTTPS,34.0,1,81.0,112.0,64.0,50.0
292250,utm,ips,alert,Japan,LLB- Connect,wan,Local_LAN,undefined,dropped,6.0,HTTPS,39.0,0,0.0,0.0,0.0,50.0
292870,traffic,forward,notice,Japan,LLB- Connect,wan,Local_LAN,undefined,client-rst,6.0,HTTPS,39.0,1,33.0,112.0,64.0,50.0

In [22]:
cp['threat'] = cp.crscore.apply(lambda x: 3 if x >= 50 else 2 if x >= 30 else 1 if x >= 5 else 0)
cp.threat.value_counts()

0    362046
2     10238
1      6549
3         4
Name: threat, dtype: int64

In [23]:
cp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 378837 entries, 0 to 380836
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   type         378837 non-null  object
 1   subtype      378837 non-null  object
 2   level        378837 non-null  object
 3   srccountry   378837 non-null  object
 4   srcintf      378837 non-null  object
 5   srcintfrole  378837 non-null  object
 6   dstintf      378837 non-null  object
 7   dstintfrole  378837 non-null  object
 8   action       378837 non-null  object
 9   proto        378837 non-null  float64
 10  service      378837 non-null  object
 11  policyid     378837 non-null  float64
 12  appcat       378837 non-null  int64
 13  duration     378837 non-null  float64
 14  sentbyte     378837 non-null  float64
 15  rcvdbyte     378837 non-null  float64
 16  crscore      378837 non-null  float64
 17  threat       378837 non-null  int64
dtypes: float64(6), int64(2), object(10)
memory usage: 54.9+ MB

In [24]:
cp.proto.value_counts()

6.0     283409
1.0      93850
17.0      1566
47.0        12
Name: proto, dtype: int64

In [25]:
cp.threat.value_counts()

0    362046
2     10238
1      6549
3         4
Name: threat, dtype: int64

In [26]:
cp.loc[cp.threat < 1, 'threat'] = cp[cp.threat != 3].groupby('proto')['proto'].transform('count').apply(lambda x: 1 if x < 1000 else 0)
cp.threat.value_counts()

0    362046
2     10238
1      6549
3         4
Name: threat, dtype: int64

In [27]:
cp.service.value_counts()

HTTPS          251556
PING            93697
FTPS            14699
NHP-FLUX         4188
ForFTP_DATA      2154
                ...
tcp/8092            1
tcp/11119           1
tcp/28573           1
tcp/52526           1
tcp/10223           1
Name: service, Length: 935, dtype: int64

In [28]:
serv = cp.service.value_counts()
print(serv.count())
serv[serv > 1000].count()

935

7

In [29]:
cp.threat.value_counts()

0    362046
2     10238
1      6549
3         4
Name: threat, dtype: int64

In [30]:
cp.loc[cp.threat < 1, 'threat'] = cp[cp.threat < 1]['service'].apply(lambda x: 1 if serv[x] < 1000 else 0)
cp.threat.value_counts()

0    361756
2     10238
1      6839
3         4
Name: threat, dtype: int64

In [31]:
cp.level.value_counts()

notice     378495
warning       339
alert           3
Name: level, dtype: int64

In [32]:
cp.loc[cp.level == 'warning','threat'] = 2

In [33]:
cp.threat.value_counts()

0    361756
2     10577
1      6500
3         4
Name: threat, dtype: int64

In [34]:
cp.loc[cp.level == 'alert','threat'] = 3
cp.threat.value_counts()

0    361756
2     10576
1      6500
3         5
Name: threat, dtype: int64

We have successfully created a new column, `threat`, which is the level of severity of the attack. It will be used as the target variable in our machine learning model.

# Encoding
In order to be able to use the dataset in our machine learning model, we need to encode the categorical features. For this, we will simply map the categorical features in the dataset to numerical values.

In [35]:
unique(cp)

type

traffic    378834
utm             3
Name: type, dtype: int64


____________________________________________________________________________________________________
subtype

forward    378528
local         306
ips             3
Name: subtype, dtype: int64


____________________________________________________________________________________________________
level

notice     378495
warning       339
alert           3
Name: level, dtype: int64


____________________________________________________________________________________________________
srccountry

India            206270
United States     73812
Reserved          37919
Australia          7711
Ireland            6552
                  ...
Belize                1
Kenya                 1
Ecuador               1
Kyrgyzstan            1
Benin                 1
Name: srccountry, Length: 93, dtype: int64


____________________________________________________________________________________________________
srcintf

LLB- Connect    344217
Local_LAN        34314
unknown-0          280
root                26
Name: srcintf, dtype: int64


____________________________________________________________________________________________________
srcintfrole

wan          344217
undefined     34620
Name: srcintfrole, dtype: int64


____________________________________________________________________________________________________
dstintf

Local_LAN       344243
LLB- Connect     34594
Name: dstintf, dtype: int64


____________________________________________________________________________________________________
dstintfrole

undefined    344243
wan           34594
Name: dstintfrole, dtype: int64


____________________________________________________________________________________________________
action

client-rst    138955
accept        101654
close          95831
server-rst     25569
deny           10236
timeout         6250
ip-conn          230
dns              109
dropped            3
Name: action, dtype: int64


____________________________________________________________________________________________________
proto

6.0     283409
1.0      93850
17.0      1566
47.0        12
Name: proto, dtype: int64


____________________________________________________________________________________________________
service

HTTPS          251556
PING            93697
FTPS            14699
NHP-FLUX         4188
ForFTP_DATA      2154
                ...
tcp/8092            1
tcp/11119           1
tcp/28573           1
tcp/52526           1
tcp/10223           1
Name: service, Length: 935, dtype: int64


____________________________________________________________________________________________________
policyid

49.0    98170
59.0    45273
57.0    33024
47.0    30732
67.0    23028
60.0    19614
63.0    16804
35.0    15688
33.0    11528
34.0    11473
50.0    11457
44.0    10667
17.0     9383
56.0     7919
53.0     6365
39.0     6303
42.0     5716
48.0     3486
89.0     3234
72.0     2405
79.0     1928
52.0      949
85.0      754
87.0      635
43.0      341
0.0       306
54.0      297
75.0      251
90.0      240
82.0      203
74.0      186
73.0      157
37.0      133
76.0       55
86.0       46
80.0       36
71.0       25
81.0       18
78.0        3
88.0        2
77.0        2
65.0        1
Name: policyid, dtype: int64


____________________________________________________________________________________________________
appcat

0    316823
1     62014
Name: appcat, dtype: int64


____________________________________________________________________________________________________
duration

60.0       88693
1.0        49150
6.0        34613
5.0        12645
0.0        10774
           ...
701.0          1
2412.0         1
48720.0        1
2411.0         1
60168.0        1
Name: duration, Length: 1327, dtype: int64


____________________________________________________________________________________________________
sentbyte

36.0         84466
164.0        28431
268.0        28186
216.0        15022
132.0        12430
             ...
3092.0           1
2199.0           1
650.0            1
3028.0           1
1626171.0        1
Name: sentbyte, Length: 2712, dtype: int64


____________________________________________________________________________________________________
rcvdbyte

36.0       84466
168.0      21201
248.0      13482
132.0      11915
0.0        11400
           ...
12500.0        1
24132.0        1
14218.0        1
14077.0        1
14840.0        1
Name: rcvdbyte, Length: 15007, dtype: int64


____________________________________________________________________________________________________
crscore

0.0     362046
30.0     10238
5.0       6549
50.0         4
Name: crscore, dtype: int64


____________________________________________________________________________________________________
threat

0    361756
2     10576
1      6500
3         5
Name: threat, dtype: int64


____________________________________________________________________________________________________

In [36]:
cp.columns

Index(['type', 'subtype', 'level', 'srccountry', 'srcintf', 'srcintfrole',
       'dstintf', 'dstintfrole', 'action', 'proto', 'service', 'policyid',
       'appcat', 'duration', 'sentbyte', 'rcvdbyte', 'crscore', 'threat'],
      dtype='object')

In [37]:
cp.type.unique()

array(['traffic', 'utm'], dtype=object)

In [38]:
cp.type = cp.type.apply(lambda x: 1 if x == 'utm' else 0)

In [39]:
cp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 378837 entries, 0 to 380836
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   type         378837 non-null  int64
 1   subtype      378837 non-null  object
 2   level        378837 non-null  object
 3   srccountry   378837 non-null  object
 4   srcintf      378837 non-null  object
 5   srcintfrole  378837 non-null  object
 6   dstintf      378837 non-null  object
 7   dstintfrole  378837 non-null  object
 8   action       378837 non-null  object
 9   proto        378837 non-null  float64
 10  service      378837 non-null  object
 11  policyid     378837 non-null  float64
 12  appcat       378837 non-null  int64
 13  duration     378837 non-null  float64
 14  sentbyte     378837 non-null  float64
 15  rcvdbyte     378837 non-null  float64
 16  crscore      378837 non-null  float64
 17  threat       378837 non-null  int64
dtypes: float64(6), int64(3), object(9)
memory usage: 54.9+ MB

In [40]:
cp.subtype.unique()

array(['forward', 'local', 'ips'], dtype=object)

In [41]:
cols = cp.select_dtypes(include='object').columns.tolist()
d = {}
for col in cols:
  d[col] = cp[col].unique().tolist()
  li = cp[col].unique().tolist()
  cp[col] = cp[col].apply(lambda x: li.index(x))
d

{'subtype': ['forward', 'local', 'ips'],
 'level': ['notice', 'warning', 'alert'],
 'srccountry': ['India',
  'Reserved',
  'United States',
  'Somalia',
  'Netherlands',
  'Australia',
  'Germany',
  'Bulgaria',
  'Cyprus',
  'France',
  'Unknown',
  'Japan',
  'Malaysia',
  'United Arab Emirates',
  'Ireland',
  'Canada',
  'United Kingdom',
  'Hong Kong',
  'Bahrain',
  'Italy',
  'Singapore',
  'Sweden',
  'Brazil',
  'South Africa',
  'Korea, Republic of',
  'Czech Republic',
  'Pakistan',
  'Russian Federation',
  'Thailand',
  'Lithuania',
  'Ecuador',
  'Uzbekistan',
  'Chile',
  'Denmark',
  'Maldives',
  'Portugal',
  'China',
  'Ukraine',
  'New Zealand',
  'Mali',
  'Mongolia',
  'Ghana',
  'Oman',
  'Georgia',
  'Mauritius',
  'Turkey',
  'Taiwan',
  'Spain',
  'Argentina',
  'Saudi Arabia',
  'Finland',
  'Egypt',
  'Romania',
  'Slovenia',
  'Iraq',
  'Belize',
  'Cambodia',
  'Switzerland',
  'Sri Lanka',
  'Philippines',
  'Nigeria',
  'Ethiopia',
  'Serbia',
  'Iran, Islamic Republic of',
  'Armenia',
  'Tunisia',
  'Israel',
  'Belgium',
  'Mexico',
  'Tanzania, United Republic of',
  'Colombia',
  'Isle of Man',
  'El Salvador',
  'Azerbaijan',
  'Indonesia',
  'Greece',
  'Malta',
  'Jordan',
  'Kenya',
  'Belarus',
  'Kazakhstan',
  'Bosnia and Herzegovina',
  'Croatia',
  'Hungary',
  'Qatar',
  'Latvia',
  'Vietnam',
  'Bangladesh',
  'Estonia',
  'Kyrgyzstan',
  'Benin',
  'Albania',
  'Myanmar'],
 'srcintf': ['LLB- Connect', 'Local_LAN', 'unknown-0', 'root'],
 'srcintfrole': ['wan', 'undefined'],
 'dstintf': ['Local_LAN', 'LLB- Connect'],
 'dstintfrole': ['undefined', 'wan'],
 'action': ['client-rst',
  'close',
  'accept',
  'server-rst',
  'deny',
  'timeout',
  'ip-conn',
  'dns',
  'dropped'],
 'service': ['HTTPS',
  'FTPS',
  'tcp/3349',
  'PING',
  'tcp/44094',
  'ForFTP_DATA',
  'tcp/7143',
  'NHP-FLUX',
  'DNS',
  'icmp/0/8',
  'tcp/51179',
  'tcp/2705',
  'tcp/8501',
  'tcp/8085',
  'tcp/16322',
  'udp/8081',
  'udp/5353',
  'tcp/43894',
  'tcp/58591',
  'tcp/1800',
  'tcp/2023',
  'udp/8083',
  'udp/8080',
  'tcp/9001',
  'HTTP',
  'tcp/43893',
  'tcp/6443',
  'tcp/33335',
  'tcp/8888',
  'tcp/13333',
  'tcp/40501',
  'tcp/1240',
  'tcp/11115',
  'tcp/2005',
  'tcp/2091',
  'tcp/2101',
  'tcp/2090',
  'tcp/33010',
  'udp/1027',
  'RTSP',
  'tcp/32914',
  'udp/8082',
  'tcp/30089',
  'tcp/33389',
  'SMTPS',
  'tcp/26657',
  'tcp/7366',
  'tcp/4433',
  'tcp/33896',
  'tcp/5678',
  'tcp/33000',
  'tcp/26659',
  'tcp/8546',
  'tcp/33892',
  'tcp/41433',
  'tcp/21912',
  'tcp/10433',
  'tcp/5601',
  'tcp/24413',
  'tcp/9650',
  'tcp/18546',
  'tcp/8545',
  'tcp/3789',
  'tcp/1389',
  'VDOLIVE',
  'tcp/9990',
  'tcp/61014',
  'tcp/18545',
  'tcp/16589',
  'tcp/11000',
  'tcp/7433',
  'tcp/22020',
  'tcp/55366',
  'NTP',
  'tcp/26660',
  'tcp/32371',
  'tcp/8815',
  'X-WINDOWS',
  'tcp/43389',
  'tcp/20201',
  'tcp/48942',
  'TELNET',
  'FTP',
  'tcp/8547',
  'udp/22',
  'tcp/50005',
  'tcp/5005',
  'tcp/42914',
  'tcp/49389',
  'tcp/17882',
  'tcp/8845',
  'SNMP',
  'tcp/13384',
  'tcp/1017',
  'tcp/8548',
  'udp/4000',
  'tcp/888',
  'tcp/8819',
  'tcp/8807',
  'tcp/62922',
  'tcp/8820',
  'tcp/14433',
  'tcp/8854',
  'tcp/11114',
  'tcp/15006',
  'tcp/5500',
  'tcp/54077',
  'udp/11211',
  'tcp/2006',
  'tcp/8818',
  'tcp/12433',
  'tcp/34130',
  'tcp/35366',
  'tcp/3200',
  'tcp/14330',
  'tcp/49676',
  'tcp/8934',
  'tcp/6089',
  'tcp/9089',
  'tcp/13389',
  'tcp/39389',
  'tcp/8989',
  'MS-SQL',
  'tcp/11118',
  'tcp/33905',
  'tcp/2999',
  'tcp/44273',
  'tcp/32288',
  'tcp/20412',
  'tcp/41832',
  'tcp/28222',
  'tcp/25898',
  'tcp/9195',
  'tcp/3030',
  'tcp/5107',
  'tcp/21988',
  'tcp/3433',
  'tcp/24444',
  'tcp/5050',
  'tcp/8521',
  'tcp/23390',
  'tcp/15555',
  'tcp/48380',
  'tcp/9433',
  'tcp/6802',
  'tcp/40389',
  'tcp/3189',
  'tcp/17433',
  'tcp/33809',
  'tcp/16101',
  'tcp/43898',
  'tcp/3369',
  'tcp/10000',
  'tcp/2085',
  'tcp/2105',
  'tcp/3438',
  'tcp/13571',
  'tcp/2078',
  'tcp/2108',
  'tcp/1435',
  'SIP',
  'tcp/2107',
  'tcp/2103',
  'tcp/11117',
  'tcp/21181',
  'tcp/3111',
  'tcp/3198',
  'tcp/42130',
  'tcp/3333',
  'udp/8000',
  'tcp/59101',
  'tcp/5901',
  'tcp/9527',
  'KERBEROS',
  'gre',
  'tcp/8120',
  'tcp/36584',
  'udp/1900',
  'tcp/24722',
  'tcp/5555',
  'tcp/10037',
  'tcp/46389',
  'tcp/18389',
  'tcp/5515',
  'tcp/8122',
  'tcp/8121',
  'tcp/1551',
  'tcp/14444',
  'udp/30301',
  'tcp/8512',
  'tcp/9026',
  'tcp/7234',
  'tcp/8443',
  'tcp/5539',
  'tcp/3395',
  'tcp/14578',
  'tcp/3381',
  'tcp/33069',
  'tcp/40002',
  'tcp/3397',
  'tcp/1456',
  'tcp/666',
  'tcp/5366',
  'tcp/311',
  'tcp/1110',
  'tcp/33894',
  'tcp/51433',
  'tcp/7498',
  'tcp/33189',
  'tcp/7384',
  'tcp/50988',
  'tcp/35389',
  'tcp/30000',
  'tcp/45389',
  'tcp/8125',
  'tcp/12203',
  'tcp/3137',
  'tcp/12199',
  'tcp/12201',
  'tcp/12207',
  'tcp/26',
  'tcp/3319',
  'tcp/41389',
  'tcp/50014',
  'tcp/43451',
  'tcp/22589',
  'tcp/35222',
  'tcp/39106',
  'tcp/58053',
  'tcp/50429',
  'tcp/58008',
  'tcp/15180',
  'tcp/8983',
  'tcp/51389',
  'tcp/12204',
  'tcp/8129',
  'tcp/7788',
  'tcp/2109',
  'tcp/29494',
  'tcp/8124',
  'tcp/21609',
  'DCE-RPC',
  'tcp/8117',
  'tcp/15433',
  'tcp/22051',
  'udp/19',
  'tcp/2289',
  'tcp/25637',
  'tcp/50374',
  'tcp/1414',
  'tcp/8128',
  'tcp/1015',
  'tcp/4444',
  'tcp/8127',
  'tcp/9110',
  'tcp/53890',
  'tcp/3110',
  'tcp/8119',
  'tcp/4389',
  'tcp/3365',
  'tcp/1919',
  'tcp/10026',
  'tcp/5433',
  'tcp/16666',
  'tcp/13433',
  'tcp/40994',
  'tcp/33033',
  'tcp/49830',
  'tcp/1002',
  'tcp/40995',
  'tcp/18433',
  'tcp/62044',
  'tcp/3390',
  'tcp/27429',
  'tcp/57018',
  'tcp/3387',
  'tcp/1106',
  'tcp/3309',
  'tcp/60230',
  'tcp/830',
  'tcp/11111',
  'tcp/31111',
  'tcp/541',
  'tcp/33339',
  'tcp/59963',
  'tcp/12205',
  'HQssh',
  'tcp/56295',
  'tcp/12208',
  'tcp/6366',
  'tcp/12200',
  'tcp/9179',
  'tcp/51194',
  'tcp/1741',
  'tcp/6618',
  'tcp/3005',
  'udp/7474',
  'tcp/43891',
  'tcp/40957',
  'tcp/31433',
  'tcp/33289',
  'tcp/3388',
  'tcp/6535',
  'tcp/2290',
  'tcp/646',
  'FTP_1',
  'tcp/43399',
  'tcp/41005',
  'tcp/11116',
  'tcp/20433',
  'tcp/8513',
  'tcp/151',
  'tcp/16095',
  'tcp/53389',
  'tcp/3479',
  'tcp/25555',
  'tcp/33089',
  'tcp/63390',
  'tcp/5010',
  'tcp/1911',
  'tcp/9100',
  'tcp/15005',
  'tcp/2389',
  'tcp/2299',
  'tcp/11593',
  'tcp/22015',
  'tcp/1501',
  'tcp/24424',
  'RDP',
  'tcp/131',
  'tcp/2761',
  'tcp/15366',
  'tcp/202',
  'tcp/175',
  'tcp/223',
  'tcp/1656',
  'tcp/12206',
  'tcp/28573',
  'tcp/19651',
  'tcp/63030',
  'tcp/65153',
  'tcp/26442',
  'tcp/36483',
  'tcp/23465',
  'tcp/19715',
  'tcp/12202',
  'tcp/8602',
  'tcp/8500',
  'tcp/16389',
  'tcp/3589',
  'tcp/9292',
  'tcp/2562',
  'tcp/2762',
  'tcp/21847',
  'tcp/33093',
  'tcp/23723',
  'tcp/6700',
  'tcp/19635',
  'tcp/36215',
  'tcp/21587',
  'tcp/7186',
  'tcp/7487',
  'tcp/40929',
  'tcp/801',
  'tcp/8855',
  'tcp/14000',
  'tcp/9036',
  'tcp/38409',
  'tcp/55142',
  'tcp/31906',
  'tcp/12504',
  'tcp/21126',
  'tcp/33219',
  'tcp/21961',
  'tcp/8433',
  'tcp/64338',
  'tcp/3000',
  'tcp/43890',
  'tcp/48000',
  'tcp/49999',
  'tcp/5613',
  'Tomcat-Apache',
  'tcp/21247',
  'tcp/8530',
  'tcp/38923',
  'tcp/5367',
  'udp/6881',
  'tcp/38912',
  'tcp/33333',
  'tcp/5938',
  'tcp/38955',
  'tcp/3889',
  'tcp/17316',
  'tcp/7777',
  'tcp/40404',
  'SOCKS',
  'tcp/45133',
  'tcp/38916',
  'tcp/51165',
  'tcp/1444',
  'tcp/38937',
  'tcp/50007',
  'tcp/7351',
  'tcp/803',
  'tcp/802',
  'tcp/3391',
  'tcp/2018',
  'tcp/777',
  'tcp/3392',
  'tcp/4899',
  'tcp/3394',
  'tcp/1521',
  'tcp/1214',
  'tcp/38957',
  'tcp/1212',
  'tcp/48389',
  'tcp/3393',
  'IKE',
  'tcp/3385',
  'tcp/7194',
  'tcp/3386',
  'tcp/38919',
  'tcp/51154',
  'tcp/37628',
  'tcp/45366',
  'tcp/7089',
  'tcp/23341',
  'tcp/60083',
  'tcp/7488',
  'tcp/39099',
  'tcp/21466',
  'tcp/33332',
  'tcp/38954',
  'tcp/41007',
  'tcp/24567',
  'tcp/41023',
  'tcp/7322',
  'tcp/62584',
  'tcp/16240',
  'tcp/32928',
  'tcp/40839',
  'tcp/47347',
  'tcp/45360',
  'tcp/47260',
  'tcp/62767',
  'tcp/38905',
  'tcp/46715',
  'tcp/2468',
  'tcp/31389',
  'tcp/7276',
  'tcp/30015',
  'tcp/14333',
  'tcp/3131',
  'tcp/1109',
  'tcp/19389',
  'tcp/38917',
  'tcp/4089',
  'tcp/53892',
  'tcp/6565',
  'tcp/1981',
  'tcp/33110',
  'tcp/33331',
  'tcp/38906',
  'test1',
  'tcp/12100',
  'udp/427',
  'udp/139',
  'tcp/8880',
  'tcp/8531',
  'tcp/31853',
  'tcp/45107',
  'tcp/16173',
  'tcp/45890',
  'tcp/5513',
  'tcp/17703',
  'tcp/9736',
  'tcp/51140',
  'tcp/1244',
  'tcp/43771',
  'tcp/34123',
  'tcp/10039',
  'tcp/7789',
  'tcp/1022',
  'tcp/2224',
  'tcp/38913',
  'tcp/999',
  'tcp/52529',
  'IRC',
  'tcp/7353',
  'tcp/2300',
  'MYSQL',
  'tcp/41056',
  'tcp/43897',
  'tcp/41024',
  'tcp/1727',
  'tcp/10001',
  'tcp/41059',
  'tcp/8812',
  'tcp/38918',
  'tcp/26666',
  'tcp/41039',
  'tcp/32001',
  'tcp/33899',
  'tcp/41035',
  'tcp/36745',
  'tcp/29002',
  'tcp/58680',
  'tcp/39172',
  'tcp/53255',
  'tcp/53883',
  'tcp/28871',
  'tcp/64367',
  'tcp/6389',
  'tcp/26948',
  'tcp/2526',
  'tcp/19872',
  'tcp/4489',
  'tcp/12345',
  'tcp/2727',
  'tcp/21234',
  'tcp/26805',
  'tcp/32400',
  'tcp/28100',
  'tcp/31317',
  'tcp/8291',
  'tcp/38922',
  'tcp/32022',
  'tcp/3399',
  'tcp/21505',
  'tcp/5369',
  'tcp/11433',
  'tcp/1455',
  'tcp/3289',
  'tcp/4003',
  'tcp/1533',
  'tcp/3383',
  'tcp/38964',
  'tcp/8181',
  'tcp/12126',
  'tcp/155',
  'tcp/7439',
  'tcp/21433',
  'tcp/32768',
  'tcp/6767',
  'tcp/3324',
  'tcp/13310',
  'tcp/6379',
  'tcp/36489',
  'tcp/8532',
  'tcp/33065',
  'tcp/13131',
  'PPTP',
  'tcp/850',
  'tcp/52385',
  'tcp/4171',
  'tcp/1575',
  'udp/1029',
  'tcp/1977',
  'tcp/8533',
  'tcp/12162',
  'tcp/16433',
  'tcp/8088',
  'tcp/53891',
  'tcp/20004',
  'tcp/38947',
  'tcp/23259',
  'tcp/1189',
  'tcp/7078',
  'tcp/3585',
  'tcp/5233',
  'tcp/10089',
  'tcp/8111',
  'tcp/8536',
  'tcp/7175',
  'tcp/3335',
  'tcp/6240',
  'tcp/39036',
  'tcp/39090',
  'tcp/15447',
  'tcp/27381',
  'tcp/53693',
  'tcp/51392',
  'tcp/31900',
  'tcp/37953',
  'tcp/62204',
  'tcp/18606',
  'tcp/43895',
  'tcp/27017',
  'tcp/4567',
  'tcp/17010',
  'tcp/16169',
  'tcp/9910',
  'tcp/12405',
  'tcp/8540',
  'tcp/7389',
  'tcp/5566',
  'tcp/40003',
  'tcp/38999',
  'tcp/47828',
  'tcp/34311',
  'tcp/11833',
  'tcp/5090',
  'tcp/15001',
  'tcp/6100',
  'tcp/8068',
  'tcp/13877',
  'tcp/35971',
  'tcp/9006',
  'tcp/21135',
  'tcp/5520',
  'tcp/33989',
  'tcp/3545',
  'tcp/33246',
  'tcp/1111',
  'tcp/60889',
  'tcp/45271',
  'tcp/3489',
  'tcp/5368',
  'tcp/30389',
  'tcp/2433',
  'tcp/804',
  'tcp/8544',
  'tcp/9000',
  'tcp/33898',
  'udp/1434',
  'tcp/34689',
  'tcp/10567',
  'tcp/23761',
  'tcp/57050',
  'tcp/57117',
  'tcp/32345',
  'tcp/8716',
  'tcp/41405',
  'tcp/40443',
  'tcp/56971',
  'tcp/6881',
  'tcp/37922',
  'tcp/37018',
  'tcp/33589',
  'tcp/22074',
  'tcp/48530',
  'tcp/34404',
  'tcp/3017',
  'tcp/1201',
  'tcp/9002',
  'tcp/50019',
  'tcp/50453',
  'tcp/39915',
  'tcp/39433',
  'tcp/45640',
  'tcp/12723',
  'tcp/41217',
  'tcp/32219',
  'tcp/15495',
  'tcp/8389',
  'tcp/52526',
  'tcp/8515',
  'tcp/1850',
  'tcp/11119',
  'tcp/8092',
  'tcp/8516',
  'tcp/1980',
  'tcp/50009',
  'tcp/8523',
  'tcp/17890',
  'tcp/1',
  'tcp/3398',
  'tcp/1352',
  'tcp/6671',
  'tcp/12587',
  'tcp/34673',
  'tcp/28109',
  'tcp/46432',
  'tcp/16175',
  'tcp/15831',
  'tcp/40945',
  'tcp/6433',
  'tcp/8800',
  'tcp/60042',
  'tcp/5984',
  'tcp/52389',
  'tcp/23389',
  'tcp/7380',
  'tcp/46130',
  'tcp/15871',
  'tcp/7071',
  'tcp/6900',
  'tcp/8139',
  'tcp/20266',
  'tcp/50804',
  'tcp/41285',
  'tcp/7264',
  'tcp/8079',
  'tcp/37182',
  'tcp/63955',
  'tcp/27502',
  'tcp/62218',
  'tcp/45541',
  'tcp/5522',
  'tcp/12363',
  'tcp/40596',
  'tcp/16699',
  'tcp/5255',
  'tcp/11888',
  'tcp/5256',
  'tcp/7491',
  'tcp/29665',
  'tcp/51172',
  'tcp/9500',
  'tcp/33096',
  'tcp/2022',
  'tcp/10035',
  'tcp/12967',
  'tcp/42575',
  'tcp/37875',
  'tcp/58228',
  'tcp/58837',
  'tcp/34415',
  'tcp/52103',
  'tcp/52304',
  'tcp/47786',
  'tcp/8327',
  'tcp/10714',
  'tcp/8453',
  'tcp/5254',
  'tcp/51129',
  'tcp/22587',
  'tcp/9977',
  'tcp/8933',
  'tcp/190',
  'tcp/5257',
  'tcp/44489',
  'IMAP',
  'tcp/33903',
  'tcp/40004',
  'tcp/25948',
  'tcp/62054',
  'tcp/18426',
  'tcp/27455',
  'tcp/34936',
  'tcp/48177',
  'tcp/32752',
  'tcp/60362',
  'tcp/9200',
  'tcp/4412',
  'tcp/43896',
  'tcp/15389',
  'udp/523',
  'tcp/47468',
  'tcp/5260',
  'tcp/3382',
  'tcp/9989',
  'tcp/5259',
  'tcp/6999',
  'tcp/21337',
  'tcp/6489',
  'tcp/5258',
  'tcp/12477',
  'tcp/5724',
  'tcp/15520',
  'tcp/16662',
  'tcp/47116',
  'tcp/53797',
  'tcp/65294',
  'tcp/42745',
  'tcp/42888',
  'tcp/1337',
  'tcp/40941',
  'tcp/17376',
  'tcp/5262',
  'tcp/43899',
  'tcp/5261',
  'tcp/8008',
  'tcp/1202',
  'tcp/41108',
  'tcp/40044',
  'tcp/8899',
  'tcp/5389',
  'tcp/24163',
  'tcp/15719',
  'tcp/55171',
  'tcp/58632',
  'tcp/11325',
  'tcp/49875',
  'tcp/30317',
  'tcp/11035',
  'tcp/20011',
  'tcp/35613',
  'tcp/32786',
  'tcp/3359',
  'tcp/40969',
  'tcp/6703',
  'tcp/60086',
  'tcp/154',
  'tcp/6697',
  'tcp/20681',
  'tcp/40940',
  'tcp/8090',
  'tcp/28828',
  'tcp/55078',
  'tcp/8223',
  'tcp/60846',
  'tcp/15246',
  'tcp/30199',
  'tcp/41490',
  'tcp/26893',
  'tcp/10036',
  'tcp/2003',
  'tcp/40952',
  'tcp/40971',
  'tcp/8549',
  'tcp/40953',
  'tcp/48097',
  'tcp/1979',
  'tcp/61927',
  'tcp/40982',
  'tcp/27786',
  'tcp/5263',
  'tcp/23577',
  'tcp/13000',
  'tcp/7394',
  'tcp/6500',
  'tcp/23177',
  'tcp/25163',
  'tcp/16134',
  'tcp/6908',
  'tcp/38402',
  'tcp/15852',
  'tcp/10326',
  'tcp/40818',
  'tcp/13020',
  'tcp/7178',
  'tcp/5563',
  'tcp/1089',
  'tcp/5061',
  'tcp/3379',
  'tcp/8873',
  'tcp/9315',
  'tcp/25366',
  'tcp/22731',
  'tcp/26180',
  'tcp/8874',
  'tcp/3396',
  'tcp/33090',
  'udp/40810',
  'tcp/51789',
  'tcp/44389',
  'tcp/213',
  'tcp/36389',
  'tcp/23260',
  'tcp/31388',
  'tcp/60890',
  'tcp/54469',
  'tcp/11569',
  'tcp/11442',
  'tcp/6090',
  'tcp/47209',
  'tcp/35157',
  'tcp/33390',
  'tcp/12000',
  'tcp/6560',
  'tcp/52314',
  'tcp/7204',
  'tcp/3339',
  'tcp/40356',
  'tcp/63564',
  'tcp/2020',
  'tcp/16457',
  'tcp/12350',
  'tcp/40983',
  'tcp/8011',
  'tcp/14673',
  'tcp/33891',
  'tcp/64256',
  'tcp/30405',
  'tcp/54589',
  'tcp/12058',
  'tcp/27297',
  'tcp/38403',
  'tcp/31936',
  'tcp/16682',
  'tcp/12354',
  'tcp/8044',
  'tcp/8591',
  'tcp/53767',
  'tcp/5400',
  'tcp/12355',
  'tcp/8589',
  'tcp/8517',
  'tcp/32182',
  'tcp/12353',
  'tcp/2001',
  'tcp/12349',
  'tcp/15000',
  'tcp/12351',
  'tcp/12352',
  'AOL',
  'tcp/7225',
  'tcp/48554',
  'tcp/24611',
  'tcp/16343',
  'tcp/57762',
  'tcp/5373',
  'tcp/49501',
  'tcp/6888',
  'tcp/54528',
  'tcp/65343',
  'tcp/23333',
  'tcp/33890',
  'tcp/55778',
  'tcp/51159',
  'tcp/6602',
  'tcp/40996',
  'tcp/22682',
  'tcp/32523',
  'tcp/12356',
  'tcp/444',
  'tcp/12357',
  'tcp/53208',
  'tcp/31023',
  'tcp/47389',
  'tcp/9028',
  'tcp/2362',
  'tcp/8333',
  'tcp/43594',
  'tcp/50835',
  'tcp/7895',
  'tcp/57205',
  'tcp/38049',
  'tcp/59469',
  'tcp/38866',
  'tcp/55573',
  'tcp/9034',
  'tcp/9031',
  'tcp/10223']}

In [42]:
cp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 378837 entries, 0 to 380836
Data columns (total 18 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   type         378837 non-null  int64
 1   subtype      378837 non-null  int64
 2   level        378837 non-null  int64
 3   srccountry   378837 non-null  int64
 4   srcintf      378837 non-null  int64
 5   srcintfrole  378837 non-null  int64
 6   dstintf      378837 non-null  int64
 7   dstintfrole  378837 non-null  int64
 8   action       378837 non-null  int64
 9   proto        378837 non-null  float64
 10  service      378837 non-null  int64
 11  policyid     378837 non-null  float64
 12  appcat       378837 non-null  int64
 13  duration     378837 non-null  float64
 14  sentbyte     378837 non-null  float64
 15  rcvdbyte     378837 non-null  float64
 16  crscore      378837 non-null  float64
 17  threat       378837 non-null  int64
dtypes: float64(6), int64(12)
memory usage: 54.9 MB

We now have successfully encoded the categorical features in the dataset. We can now save the dataset to a CSV file.

In [43]:
cp.to_csv('df.csv', index=False)

# Threat Classification

We now create a new dataset with only the rows with the `threat` value greater than 0. This will be used to train a machine learning model to classify the attacks with respect to their severity.

In [44]:
cp.tail()

,type,subtype,level,srccountry,srcintf,srcintfrole,dstintf,dstintfrole,action,proto,service,policyid,appcat,duration,sentbyte,rcvdbyte,crscore,threat
380832,0,0,0,16,0,0,0,0,2,1.0,3,49.0,0,70.0,132.0,172.0,0.0,0
380833,0,0,0,0,0,0,0,0,1,6.0,0,60.0,0,3.0,416.0,9096.0,0.0,0
380834,0,0,0,2,0,0,0,0,0,6.0,0,67.0,0,6.0,216.0,248.0,0.0,0
380835,0,0,0,0,0,0,0,0,0,6.0,0,49.0,0,19.0,320.0,2530.0,0.0,0
380836,0,0,0,0,0,0,0,0,0,6.0,1,63.0,0,6.0,124.0,244.0,0.0,0

In [45]:
cp.threat.value_counts()

0    361756
2     10576
1      6500
3         5
Name: threat, dtype: int64

In [47]:
threat = cp[cp.threat > 0]
threat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17081 entries, 64 to 380831
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   type         17081 non-null  int64
 1   subtype      17081 non-null  int64
 2   level        17081 non-null  int64
 3   srccountry   17081 non-null  int64
 4   srcintf      17081 non-null  int64
 5   srcintfrole  17081 non-null  int64
 6   dstintf      17081 non-null  int64
 7   dstintfrole  17081 non-null  int64
 8   action       17081 non-null  int64
 9   proto        17081 non-null  float64
 10  service      17081 non-null  int64
 11  policyid     17081 non-null  float64
 12  appcat       17081 non-null  int64
 13  duration     17081 non-null  float64
 14  sentbyte     17081 non-null  float64
 15  rcvdbyte     17081 non-null  float64
 16  crscore      17081 non-null  float64
 17  threat       17081 non-null  int64
dtypes: float64(6), int64(12)
memory usage: 2.5 MB

In [48]:
threat.to_csv('threat.csv', index=False)